version: "3.7"

services:
  app:
    build: .
    container_name: rentx
    ports:
     - 3333:3333
    volumes:
      - .:/usr/app
    depends_on: 
      - database_rentx
    network_mode: host
  database_rentx:
    image: postgres
    container_name: database_rentx
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes: 
      - pgdata:/data/postgres
    network_mode: host

volumes: 
  pgdata: 
    driver: local
    