version: "3.7"

services:
  # app:
  #   build: .
  #   ports:
  #    - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   depends_on:
  #     - database
  #     - redis
  #   network_mode: host

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
